### ISSUE TITLE
Integration failed with a error [ exceeded max number of iterations ]

### ISSUE THREAD

**Issue by zx8754** [zhanxw/rvtests#65]
I am running below command:

```
rvtest --inVcf ... \
--noweb \
--pheno ... --pheno-name ... \
--covar ... --covar-name ... \
--siteFile ... \
--geneFile $fileRefUCSC \
--kernel skato \
--out ...
```
What is the meaning of this error?

```
...
[INFO]  Gene LILRA1 has 0 variants, skipping
[INFO]  Gene RAB35 has 0 variants, skipping
Integration failed with a error [ exceeded max number of iterations ]
Integration failed with a error [ exceeded max number of iterations ]
[INFO]  Gene MIR609 has 0 variants, skipping
[INFO]  Gene NAGK has 0 variants, skipping
...
```

**Comment by zhanxw** [comment]
SKAT-O test will internally perform numeric integration. The errors about integration means this algorithm failed. 

Sorry about these error message although I have tried to avoid them.

Would you mind send example inputs so that I can reproduce/fix this error?
You can use `--outputRaw` option combined with the problematic gene `--gene RAB35`.
Then you will get some extra files with covariate, genotypes, and phenotypes. 
These will be helpful for debug.
